version: "3.7"

services:

  database:
    build:
      context: ./registration-database
    image: registration-database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    volumes:
      - debug_db_data:/var/lib/mysql
      - ./registration-database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./registration-database/mysqld_custom:/etc/mysql/conf.d 
    ports:
      - "3306:3306" 
    restart: always

  webserver:
    build: 
      context: ./registration-webserver
    image: registration-webserver
    # mount point for application in tomcat
    volumes:
      - ./app/target/UserSignup:/usr/local/tomcat/webapps/UserSignup
    links:
      - database:registration-database
    # open ports for tomcat and remote debugging
    ports:
      - "8085:8080" 
      - "8000:8000"
    restart: always

volumes:
  debug_db_data: 
